import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./_components/navbar";
import "./globals.css";
import { getProfile } from "./_lib/services/userService";

const geistSans = localFont({
  src: "./_assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./_assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CynxHost",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getProfile();

  return (
    <html lang="en">
    </html>
  );
}
